import fs from "node:fs";
import path from "node:path";

import type { RecallResponse } from "./types.js";
import {
  formatProjectContextArtifact,
  rehydrateProjectContext,
} from "./rehydrate.js";

export type AttachTarget = "claude";

export type AttachOptions = {
  tool: AttachTarget;
  outputPath?: string;
  cwd?: string;
};

export type AttachResult = {
  tool: AttachTarget;
  path: string;
};

function defaultOutputPath(tool: AttachTarget, cwd: string): string {
  switch (tool) {
    case "claude":
      return path.join(cwd, ".claude", "memshare-context.md");
  }
}

function formatClaudeArtifact(response: RecallResponse): string {
  const context = rehydrateProjectContext(response);
  const rendered = formatProjectContextArtifact(context);

  return [
    "<!-- Generated by memshare attach --tool claude. -->",
    "<!-- Refresh this file by rerunning the same memshare attach command. -->",
    "",
    rendered,
  ].join("\n");
}

export function attachContext(
  response: RecallResponse,
  options: AttachOptions,
): AttachResult {
  const cwd = options.cwd ?? process.cwd();
  const outputPath = path.resolve(
    cwd,
    options.outputPath ?? defaultOutputPath(options.tool, cwd),
  );
  const directory = path.dirname(outputPath);

  fs.mkdirSync(directory, { recursive: true });

  const content = formatClaudeArtifact(response);
  fs.writeFileSync(outputPath, `${content}\n`, "utf8");

  return {
    tool: options.tool,
    path: outputPath,
  };
}
